### ISSUE TITLE
Issues: npm run build

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#11]
I've been having some issues getting this wiki to compile correctly. I've set up some test .md files from some of my old notes, but I keep getting the below error:

```
npm run build

> buuk@2.1.4 build /home/christopher/buk
> cross-env NODE_ENV=production webpack --progress --hide-modules && npm run transpile

sh: 1: cross-env: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

Looking up the error 127 issue online, I've also run the following commands to see if they helped:
```
sudo npm install -g http-server
apt-get install nodejs-legacy
```

My current environment for this is Ubuntu Linux Subsystem for Windows, but I also have a Linux box running Elementary OS (Ubuntu based) running into the same issues. 
npm --version: 1.3.10
nodejs --version: 0.10.25

Any tips?

**Comment by hang-up** [comment]
It seems to be related as to how Debian/Ubuntu is handling node binary name.
https://stackoverflow.com/questions/21168141/cannot-install-packages-using-node-package-manager-in-ubuntu

Did you try running `sudo apt-get install nodejs-legacy` ? (you didn't `sudo` in your given command)
If so what's the error? 

Btw, `v3.0` is coming out sometime this week with new building processes!

**Comment by lloyd094** [comment]
Ah! Sorry about that, yes I used `sudo`. Both `nodejs-legacy` and `http-server` are installed. Error is same as the original post.

In regards to `v3.0`, that is exciting news, and hopefully removes the bug altogether.

**Comment by hang-up** [comment]
Weird, did you try uninstalling nodejs and reinstalling? 

Maybe this will help https://askubuntu.com/a/702162 (the comments section?)

**Comment by lloyd094** [comment]
I tried uninstalling everything (`nodejs`, `nodejs-legacy`, and `npm`), however it doesn't appear to have fixed it. The error this time is:

```
npm run build

> buuk@2.1.4 build /home/christopher/buk
> cross-env NODE_ENV=production webpack --progress --hide-modules && npm run transpile

sh: 1: cross-env: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! buuk@2.1.4 build: `cross-env NODE_ENV=production webpack --progress --hide-modules && npm run transpile`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the buuk@2.1.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/christopher/.npm/_logs/2017-06-22T00_25_31_343Z-debug.log
```

Hopefully, v3.0 fixes all this, but still a strange error.

**Comment by hang-up** [comment]
Did you `npm install`? 
Looks like you are missing the `node_modules` folder altogether.

**Comment by lloyd094** [comment]
That would be the issue. Seems to work fine now. Thanks for your help!
