### ISSUE TITLE
Feature Parity with Typora

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#12]
I personally use Typora for my Markdown documents because of the features it provides. A few of these features (Mathjax, Graphs, bullets, Table of Contents, and pictures) _based on previous .md documents_, don't work with Bük, instead showing code. Is there a possibility to have these features on Bük?

**Comment by hang-up** [comment]
Bük uses [markdown-it](https://github.com/markdown-it/markdown-it) as its underlying parser so any non conventional markdown features will require the use of a markdown-it-plugin. A list is available here: https://www.npmjs.com/browse/keyword/markdown-it-plugin

What's for sure is: 
* Bullets will get fixed in the next patch version. 
* Images are supposed to be already supported (https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#images)

If you have specific features you want to implement, feel free to send pull requests with updates!

**Comment by lloyd094** [comment]
I will have to play with pictures a bit more it appears. Glad to hear bullets will be fixed!

In regards to the npm plugins, are there any specific instructions on how to use them with Bük?

Thank you!

**Comment by hang-up** [comment]
Yes! Basic implementations for plugins goes as follow:
1) `npm install #name-of-plugin#`
2) Activate the plugin in `src/js/bootstrap/renderBootstrap.js` 
3) (Optional) From experience, lots of plugin uses ES6, so you'll need to put an exception telling webpack not to uglify it. Just add `#name-of-plugin#` at line 36 of `build/webpack.config.js`

I would heavily recommend setting up a manifest key under the `options` member since a plugin can considerably increase the size, thus the loading time of output scripts.

**Comment by lloyd094** [comment]
Thank you for the feedback! Right now I'm messing around with npm, but it's honestly rather confusing. Would you consider throwing up a quick page on of how to add a plugin? (just some random one for example). I think that would be incredibly helpful.

Thank you again!

**Comment by hang-up** [comment]
Working on updating the docs with an `Extending renderer` article.
Thanks for sticking with Bük!

**Comment by lloyd094** [comment]
Great! That will be most helpful. Thank you.

**Comment by hang-up** [comment]
I made a few minor changes in `v3.0.2` regarding plugins, hopefully it should make things clearer. 
I also created a guide on extending the renderer, you'll find it [here](https://buuk.groundedrob.com/#/usage-extending-renderer)!

**Comment by lloyd094** [comment]
Fantastic, thank you! Unfortunately your link leads to a blank page...?

**Comment by hang-up** [comment]
It might have been cached by your service worker (I'll need to fix that in the next minor release).

Either update your service worker (closing the tab usually does the trick) or clear your cache or go in incognito mode!

**Comment by lloyd094** [comment]
Fantastic - that worked! The instructions are great, and the additional edit of `renderBootstratp.js` is helpful.

Following your instructions, I still happen to run into a persistent error regardless of what plugin I attempt to install. Maybe I'm missing a step.

For this, I am trying to use the plugin `markdown-it-github-toc`:

```
npm install markdown-it-github-toc --save-dev
buuk@3.0.2 /home/christopher/buk
└── markdown-it-github-toc@3.2.4  extraneous

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.2
```

Then I add the line under `renderBootstrap.js`:
`.use(require('markdown-it-github-toc'))`

FInally, the build:
```
npm run build

> buuk@3.0.2 build /home/christopher/buk
> cross-env NODE_ENV=production node build/build.js

⠴ building for productionHash: 9dd764e8676bd4796354
Version: webpack 2.6.1
Time: 12448ms
          Asset     Size  Chunks                    Chunk Names
      vendor.js  2.58 MB       0  [emitted]  [big]  vendor
      bundle.js   314 kB       1  [emitted]  [big]  bundle
    manifest.js  1.43 kB       2  [emitted]         manifest
  vendor.js.map   3.1 MB       0  [emitted]         vendor
  bundle.js.map   755 kB       1  [emitted]         bundle
manifest.js.map  14.3 kB       2  [emitted]         manifest

ERROR in vendor.js from UglifyJs
Unexpected token: name (gstate) [./~/markdown-it-github-toc/src/index.bundle.js:108,0][vendor.js:56391,6]

⚠ Deleting sw...
ℹ Service worker deleted
✔ Build complete.
```

Any clue as to what's happening?

**Comment by hang-up** [comment]
After taking a quick look at the source code,`markdown-it-github-toc` is making use of ES6 features: https://github.com/tylingsoft/markdown-it-github-toc/blob/master/src/index.js 

This is then a case of Webpack caveats: webpack can't uglify ES6 code, you'll need to exclude the plugin in `build/webpack.config.js` at `line 36`, add the plugin to the the list of the excluded ones:

```javascript               
exclude: /node_modules\/(?!(markdown-it-highlightjs|markdown-it-mermaid|markdown-it-github-toc)\/).*/, // https://github.com/webpack/webpack/issues/2031
```

**Comment by lloyd094** [comment]
This fixes that! Thanks again. Now I should be able to use plugins and continue using this amazing piece of software. Keep up the awesome work!

**Comment by hang-up** [comment]
Typora feature parity is getting there! `v3.0.3` introduces:
* Checkbox
* Latex support
* Graph support (assuming those are UML graph): see how to toggle `uml` option

More info in the  [release note](https://github.com/hang-up/buuk/releases/tag/v3.0.3).
