### ISSUE TITLE
Update Option / Instructions

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#17]
I'm unsure if the option already exists, but is there a way to update to the latest version off git without having to repopulate the manifest / renderBootstrap / etc?

If there is, would you consider also making an entry on your demo site as to how to do so? I think this would be useful to know.

**Comment by hang-up** [comment]
Unfortunately no, every time a new version comes out, you'll need to update the manifest with your own markdown. Manifests are made to be backward compatbile, so you'd only need to write it once and then import it to any new fresh installation of Bük.

As for `renderBootstrap`, if you think of a feature might be useful for others, feel free to submit a **pull request**, I'd gladly review it :) !

**Comment by lloyd094** [comment]
Good to know about the manifest!

As for the `renderBootstrap`, I don't know if it's a possible feature... But it might be nice to have a file specifically for plugins, so that way if anything changes, it can still get the plugins selections without having to re-add those. That's the only way I could personally think of improving it.

**Comment by hang-up** [comment]
What I might do for the next few minor releases is to gradually implement optional plugins to extend the renderer? That way you could just comment / uncomment plugins to include them in `bundle.js`.

How does that sound?

**Comment by lloyd094** [comment]
Honestly, that sounds pretty great - thanks a ton for all the help with this.
