### ISSUE TITLE
Theme Issues

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#19]
Leaving plugins out of the picture, both the default (GitHub?) and Amblin themes have issues showing different things.

Default Theme:
- No Bold
- No italics
- Blurry wording (appears to be due to letter spacing?)
- (possible) Spacing in general.

Amblin Theme:
(looks much better honestly, but still missing things)
- No bullets

To explain visually, attached are 3 pictures: the source, the default theme, and the amblin theme:

**Default**
![1source](https://user-images.githubusercontent.com/22482891/27888013-aec599fa-6198-11e7-8df2-9e2af1be4fd8.PNG)

**GitHub**
![2github](https://user-images.githubusercontent.com/22482891/27888055-e3221296-6198-11e7-9e19-41c8bc44114d.png)

**Amblin**
![3amblin](https://user-images.githubusercontent.com/22482891/27888059-eccb3246-6198-11e7-84f7-3031ff4c88d7.png)

Hope that helps! Let me know if I can provide other information for you!

**Comment by hang-up** [comment]
Concerning the default theme, italics seem to be working fine on your screenshots? As for bolding, things seem to be working well on my side too. 
Can you provide a snippet of your markdown?

I'll look into the blurry working and the spacing/kerning of characters in the next patch release!

Concerning Amblin I'll be honest and tell you I didn't code it. As a matter of fact, Bük is seemingly compatible with `Marked` themes. 
A list of theme can be found [here!](http://markedstyle.com/styles) 

*Keep in mind I can't guarantee how a marked theme will react with Bük, and any issue you might encounter with the rendering is out of my scope unfortunately.*

**Comment by lloyd094** [comment]
Ah, apologies about the italics. I didn't notice, as I find them rather hard to tell apart. I think that may be due to the spacing.

In addition, I might have mixed up communication: the screenshots in order are: Source, Default, Amblin. Source a screenshot from Typora source view, while the other two are the two themes in Firefox.

Showing with my view on the default theme, bolding does not work. I'll try a different web browser tomorrow just to check, and I'll find out the exact FireFox details just in case.

As for further themes (and Amblin), I'll take a look! Thanks for the link!

**Comment by hang-up** [comment]
Oh, gotcha for your screenshots! 
I tested the default theme on my mac in Chrome (59.0.3071.115), Firefox (54.0.1) and Safari and all browsers seem to render fine? 

Here is what I have:
![screen shot 2017-07-08 at 21 57 33](https://user-images.githubusercontent.com/8967158/27990580-53c292ae-6429-11e7-856c-840a6c4f5727.png)

I boosted the styling for `strong` tags which will be merged in the next patch release.

**Comment by gnoejuan** [comment]
> Returns the right theme according to the manifest theme option.

> Bük is compatible with Marked 2 theme.
> If you wish to add themes or change the theme used, simply

>    Drop a scss stylesheet in resources/assets/sass/themes
>    Reference it in this bootstrapper.
>    Update the theme key in your manifest.

In regards to themes, is scss mandatory? Is it possible to go to the [repository](https://github.com/ttscoff/MarkedCustomStyles) listed on the [Marked Website](http://marked2app.com/help/Writing_Custom_CSS.html) and use the CSS themes there?

I apologize if this in not the appropriate place to ask. I've never touched SASS or any other preprocessors.

**Comment by hang-up** [comment]
You can write regular css in `.scss` files! Just make sure to name the theme file with an `.scss` extension.
But as I said a few posts above, I can't guarantee the result with other marked theme (you are more than welcomed to integrate a theme and submit a pull request though!)

**Comment by lloyd094** [comment]
The screenshots (with the odd word spacing) are on Elementary OS latest (Ubuntu Based), running Firefox 54.0. I also tried the default browser (Epiphany 3.18.11), which is powered by WebKit 2.16.3.

In further testing, I opened it up on my surface in both Edge and Firefox, and it displayed just fine. I'm wondering if this is possibly an issue with displaying on Linux? Do you have alternate Linux environments to test in?

**Comment by hang-up** [comment]
It sounds like you're right and it should be a Linux specific problem. Unfortunately I don't have a setup with a Linux distro so I can't 100% confirm your intuition on this one. 

If you happen to find the source of the problem, feel free to reopen this issue! In the meantime I'll close it since I can't take any specific targeted actions.

**Comment by lloyd094** [comment]
Just as an update, I tried opening the wiki under Vivaldi (Chromium based), and the page rendered fine. It appears that whatever Epiphany and Firefox use for their Linux font rendering is what's causing the issue. I would be willing to bet that Chrome itself also displays properly.

Don't know if it will help, but at least there's a definitive answer now.

**Comment by hang-up** [comment]
Thanks for the update! Let's hope Firefox and Epiphany will address this specific quirk in future releases!

**Comment by lloyd094** [comment]
Quick issue I've noticed: when adding themes (from the link you provided) into `/src/sass/themes` and then updating the `"theme":` option in `manifest.json`, Buk seems to fall back on the default theme regardless what happens.

For example, I tried (just for laughs) the "grump" theme. I put the file into the folder, named it `grump.scss`, and changed the theme to "grump". But when the website rendered, it loaded it in Default. 

Any ideas? Or did I do it wrong?

Edit: Also, I've just noticed that bolding in the default theme still doesn't appear to be working. Italics and underlines show, but nothing bolds.

Edit 2: Now that I'm looking closer, the other thing that's missing are `code` blocks.

**Comment by hang-up** [comment]
Did you add a new condition in `src/js/bootstrap/themeBootstrap.js`? When adding a new theme, you need to : 
1) Drop a `scss` in `src/sass/themes`
2) Update `themeBootstrap.js` with your new theme
3) Update the `theme` key in your manifest.

If Buk can't find the theme referenced in your manifest, it will automatically revert to the default theme. The reason why I decided to add an additional layer of abstraction is because I wanted to loosely couple external theme stylesheets and the manifest.

---
As for the bolding, can you send me another screenshot? Everything seemed to have been fixed on my side. 
On the other hand, I am positive code blocks work since I've been using them extensively in the documentation! (https://buuk.groundedrob.com/#/usage-manifest.json for example)

**Comment by lloyd094** [comment]
Ah! That works - adding the theme to the `themeBootstrap.js` made it recognize.
Regarding the bolding (and everything), I've ran into an interesting issue:

First, I must apologize about the code blocks - I was looking at the wrong area of the document.

I knew you kept saying things worked on your setup. Up until now, I have been working primarily in Linux. Originally, this was Bash for Windows (native Linux running on Windows), and later I moved it to elementary OS (also Ubuntu based). When it came to testing earlier on Firefox display compared to Chrome, I copied the folder and ran it on my Windows machine to double test. This is the method I was using to show earlier in this thread.

I have now installed git and nodejs on my Windows machine and used the same files to `npm run build`. The results were rather different and an interesting find - same files: one rendered on Linux, the other windows.

Bold (Linux, then Windows):
![linux-bold](https://user-images.githubusercontent.com/22482891/28236306-ae950bfa-68d7-11e7-8ac6-2356a359d254.PNG)
![windows-bold](https://user-images.githubusercontent.com/22482891/28236310-cb681560-68d7-11e7-9aab-84594a8080ad.PNG)

Table (Linux, then Windows):
![linux-table](https://user-images.githubusercontent.com/22482891/28236315-ee05a510-68d7-11e7-84f0-9f2f66f73dea.PNG)
![windows-table](https://user-images.githubusercontent.com/22482891/28236316-f8c5fe46-68d7-11e7-8c40-40a55daa96d8.PNG)

I'm not sure what's causing these issues, and I am willing to run through multiple variants of Linux this next week to see what I can figure out, but it is an interesting result nonetheless. The only things I can think of right now are:

1. Nodejs is currently broken in Linux.
2. A dependency in Linux is missing or broken.
3. Ubuntu (not overall Linux) has one of the issues above.

Hope that helps as an update, and if you'd like I can add this info over to a new thread and continue to report my findings while trying other Linux variants starting this next week.

**Comment by hang-up** [comment]
Hmmm interesting finds indeed, to be honest I have no idea what might be happening here...

Firefox seems to have different parsers for Windows and Linux? Did you try running it on Chrome in LInux or Windows?

I'm gonna mark this issue as Closed, since it is getting pretty long and the topics discussed are becoming too widespread. 
Please open a new thread to continue the findings there!
