### ISSUE TITLE
Image Support

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#20]
I thought I remembered reading somewhere that images were supported, but I cannot seem to find out how to input them. The current structure I use is: `![HoverValue.type](LocalSubfolder\File.type)`.

**Comment by hang-up** [comment]
Images are supposed to work indeed! Your syntax looks fine to me, but as an example, let's say you have a file `my-image.png`in the folder `docs/images`, you would have:

`![Alt text](docs/images/my-image.png)`

**Comment by lloyd094** [comment]
That would be the fix! Didn't think it needed the `docs` folder as well. Thank you!
