### ISSUE TITLE
Ubuntu Extra Steps

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#21]
As I've put earlier, I have run Buk on major distro OS's to see how they all work - and they all do. The distributions I've used are: 

- Manjaro
- CentOS
- Ubuntu

However, Ubuntu requires an extra step that the others do not need (the "correct" answer):
https://askubuntu.com/questions/426750/how-can-i-update-my-nodejs-to-the-latest-version

I think it may be a good idea to put this somewhere in FAQ, Setup, or Help to let people know ahead of time for those who use Ubuntu Based distributions.

**Comment by hang-up** [comment]
Are you sure it's an issue specific to Ubuntu? The link you referred to is dealing with updating nodejs in ubuntu, and I'm not sure as of how updating nodejs can resolve the parsing issue :(

**Comment by lloyd094** [comment]
I'm not sure what was causing the parsing error, but to be safe I just did fresh install of the three systems mentioned. 

Ubuntu uses older repositories that results in it being unable to `npm run build`. Using the steps located in the correct answer from the link (after cloning git, before doing `npm install` in the Bük folder), this fixes all the errors and ensures a compatible version of nodejs and npm.

**Comment by hang-up** [comment]
Oh okay! I'm going to take your words for it, I have practically zero experience with Ubuntu's source repositories.
This will get added to 3.1!
