### ISSUE TITLE
npm run build doesn't generate slugs

### ISSUE THREAD

**Issue by b-pmcg** [hang-up/buuk#30]
Hi, sorry if I'm misunderstanding how this works. I created some entries in the manifest, without defining any custom slugs. "advanced_slugs" is set to true. I thought running npm build was supposed to generate slugs in the manifest automatically based on the title property, but I didn't see this happen. I do not have md files created for the entries in the manifest yet, do I need to do this first? Thanks for your help.

**Comment by hang-up** [comment]
Hi! 
When setting `advanced_slugs` to `true`, you'll need to make sure you md follows this naming pattern: `directParentCategory-titleOfYourArticle`. So let's say for example you set up your file hierarchy in your manifest as follow:
```json
"articles" : {                            
  "Category 1": [                         
    {
      "title": "Example Article",          
      "tags": []
    }									 
  ]									 
}
``` 
you would need to have a md file named `category-1-example-article` in your `static/docs` folder. 

Basically, the manifest is just a way to make sure we link the right slug to the right file. `advanced_slugs` is particularly useful when you have multiple md files that might be named the same but under different categories (eg. Cars/tires.md and Trucks/tires.md). 
In scenarios where this might not happen (`advanced_slugs : false`), Bük will simply consider your article title as the slug and link that to your md file.

That was a good question, I'll make sure to edit the doc so we can avoid any confusion in the future!

**Comment by lloyd094** [comment]
Hey @b-pmcg, hopefully I can add to the above help and give an example from one of my projects. Keep in mind, I'm editing some of this to keep things more private, but it should be simple enough to be an example. A portion of my `manifest.json` is below:

```json
"options": {
    "advanced_slugs": true,
    "introduction": null,
    "lang": "en",
    "uml": false
  },

  "articles" : {
       "Training": [
      {
        "title": "Getting Started",
        "tags":[
          "help",
          "start",
          "log on",
          "log in"
        ],
        "slug": "T-GettingStarted"
      },
      {
        "title": "Phone Etiquette",
        "tags":[
          "phone etiquette",
          "etiquette",
          "how to talk",
          "advice"
        ],
        "slug": "T-Etiquette"
      },
   ],
}
```

Within my `/docs` folder, I have the files `T-GettingStarted.md` and `T-Etiquette.md`. Both of these files are then called on by the advanced slugs ("slug":), because I mention them directly. (I use "T-" to show it's under "training" for my organization purposes.)

Hopefully this helps?

**Comment by b-pmcg** [comment]
@hang-up  thanks for the quick response, that explains it nicely. Lets see if I'm understanding it now. I create an MD file to match the manifest schema (as in your example) then execute the build command, which will now automatically generate the slug, because it found the matching markdown file. I think I get the matching logic, I'm still unsure if the slug gets generated automatically, or if that part requires my input. Thanks for the help, I'll try it out tonight.

**Comment by hang-up** [comment]
Yup you're right! steps bulletpointed would be:
* Create your schema in `manifest.json`
* Name your md files according to how you defined them in the manifest
* `npm run build` 

I'm not sure to understand what you mean with requiring your input for slug generation?
Let me know if this works!

**Comment by hang-up** [comment]
@lloyd094 there's even more magic to the slug generation! When specifying the `slug` key on each article (ie. `"slug": "T-Etiquette"`), you don't even need to set up the `advanced_slugs` option anymore, it gets overwritten automatically ;)

**Comment by b-pmcg** [comment]
Hey @hang-up I figured it out finally. Sorry I didn't respond sooner but was busy over the week. My confusion was because, for some reason I was expecting the build process to actually write to the `manifest.json` file with the slug it create. But I see this is just done "behind the scenes." Everything you and @lloyd094 described makes sense now. Thanks for the help!
