### ISSUE TITLE
About mermaid plugin you are using

### ISSUE THREAD

**Issue by rhinenoir** [hang-up/buuk#33]
Hi , I've found that you are using the markdown-it-mermaid plugin, did it really work? I also use this plugin but it doesn't work

thanks a lot!:wink:

**Comment by lloyd094** [comment]
Hello! The version has changed since I've last used mermaid, but have you looked into the folder `/buuk/src/js/bootstrap` and uncommented the line in `renderer.js`? It should be in something that looks like:

```
        Conditional plugins.
     */
        // .use(require('markdown-it-mermaid'))
        // .use(require('markdown-it-checkbox'))
        // .use(require('markdown-it-latex'))
```

Just remove the `//` before the line, and it should work. Hope this helps? If not, I will definitely do my own tests and let you know what I get!

**Comment by hang-up** [comment]
Hi! 
To make use of uml support by markdown-it-mermad, you will need to:

1) Turn `uml` to true in your `manifest.json` under the options object
2) Uncomment line 33 in `index.html`
3) And as @lloyd094 said, uncomment `.use(require('markdown-it-mermaid'))`

Hope this helps!

**Comment by lloyd094** [comment]
@GARENFEATHER Did you end up getting mermaid running?

**Comment by rhinenoir** [comment]
@lloyd094 of course not, `markdown-it-mermaid` only replaces the content by sth like `<div class='mermaid'>xxx</div>`, not the correct one like `<svg>svg with independent style inside</svg>`

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lloyd094** [comment]
@GARENFEATHER I suppose maybe we are not understanding the issue you're having. Are you having an issue with Bük rendering mermaid, `markdown-it-mermaid` rendering your specific content, or something else entirely?

Could you post an example of code that we can try as well to get us on the same page? Also, what markdown editor do you use? Hope we can figure this out :relaxed:

**Comment by rhinenoir** [comment]
@lloyd094 Actually my issue is with the mermaid plugin and I've confirmed the bug is on `markdown-it-mermaid` itself…well, when I opened this issue I'm not sure about the fact so…
:wink: there is nothing wrong with buk, you can close the issue now
:smiley: thx for your concerning:wink:

_Sent from my PRO 6 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
