### ISSUE TITLE
buuk does not display pictures.

### ISSUE THREAD

**Issue by lloyd094** [hang-up/buuk#48]
Something I've noticed is that when running `buuk watch`, no pictures are displayed. Yet after building the site itself, pictures are shown. 

Is this an intentional design decision? Is there a way to enable it as a toggle-able feature if so?

**Comment by lloyd094** [comment]
Actually, this seems to be something that broke since I last tested with an older version: images are in the same location as before, but both `buuk watch` and `buuk build` seem to show an "X" where the pictures should be.

**Comment by hang-up** [comment]
It seems like you need to reference a relative path from your markdowns for buuk to find your pictures (`../static/img/your_image.png`).
This is indeed not ideal, I'll try to think of another way (need to update the doc in the meantime 😕  )

**Comment by lloyd094** [comment]
I can confirm, I needed to add the `../` to the beginning of my image links. Not ideal, no - but it works!

EDIT: Actually, this may prove to be better. It seems to be more compatible with other programs out there as well (such as Typora, the .md editor I use).

**Comment by hang-up** [comment]
Well in this case, I'll close the issue! 🎉
