### ISSUE TITLE
Request to add UML 

### ISSUE THREAD

**Issue by gnoejuan** [hang-up/buuk#8]
Currently I use [Typora](https://typora.io/) as a markdown editor and it supports [UML Generation](
http://support.typora.io/Draw-Diagrams-With-Markdown/). IMO, UML could help documentation quality.

**Comment by hang-up** [comment]
Hey! I'm currently using markdown-it as the underlying markdown to html parser. Not sure they have support for UML though.
I'll mark it as a feature for the next major release!
